export const VACANCY_ADD = 'VACANCY_ADD';
export const VACANCY_TOGGLE = 'VACANCY_TOGGLE';
export const VACANCY_REMOVE = 'VACANCY_REMOVE';
export const SHOW_DELETE_CONFIRM_DLG = 'SHOW_DELETE_CONFIRM_DLG';