export const VACANCY_ADD = 'VACANCY_ADD';
export const VACANCY_TOGGLE = 'VACANCY_TOGGLE';
export const VACANCY_REMOVE = 'VACANCY_REMOVE';
export const SHOW_DELETE_CONFIRM_DLG = 'SHOW_DELETE_CONFIRM_DLG';
export const SHOW_EDIT_VACANCY_DLG = 'SHOW_EDIT_VACANCY_DLG';
export const HIDE_EDIT_VACANCY_DLG = 'HIDE_EDIT_VACANCY_DLG';